color: null
description: null
fieldLayouts:
  c85da94b-2938-4bf9-8d1f-ddde124a7258:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-10T17:56:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ac975c7-db04-4145-90a3-4d21ef329794
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-10T17:58:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: df5e3056-f611-4f43-9561-ba7ee0622c93 # Quote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a15410a-c988-419e-882f-92548e413310
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-10T17:58:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fe0b41ea-1d6b-4721-92d9-ad51f4ce6038 # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09e88af4-9624-4b56-9528-d743a847e786
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-10T17:58:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a2b84830-34a0-4780-bf03-08293ba5127c # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 035011f5-b4eb-4b0a-971c-2a93eb7f9808
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b466b68-d85a-4d28-96b1-55b505c2ea05
        userCondition: null
handle: about
hasTitleField: true
icon: null
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
