color: null
description: null
fieldLayouts:
  f3870499-0044-4cc5-9db6-327fc9cdb5f2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-12T08:28:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 48cebd0f-d19e-48dc-b98a-8cd6adb688d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T11:01:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c854ee8e-d31d-41b5-a6b5-439ded6b83e4 # Section width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78ae7f8a-4654-4a2c-ad84-c5b86de801e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:45:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a2b84830-34a0-4780-bf03-08293ba5127c # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c96def6-2aa9-4848-ab2a-db963b25fa7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T11:46:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f06dd89-2dcf-4ae6-9ea2-0ffecd508fa1 # Image height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60b5748c-ab24-4e9a-b107-7d2f5e15bf64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:45:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2510f397-c34c-4a8b-b10e-fb9b14599ee6 # Featured Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8cb0cd5-b856-4053-b452-068b0a07a365
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:39:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e75f7d5c-c14a-4095-b070-a87cf4489180 # Hero title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b9da3a5-5091-4e19-8152-786506aa147c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:39:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8dff054f-3c9d-44a0-a554-925d24f53805 # Hero text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f6c6c90-1cf1-444b-8a57-52b3bc03cdaf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:39:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 882949e2-a06f-4263-95b8-dd17ccde9d50 # CTA button thext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: defc4403-2186-4515-a98e-f90209abfa39
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:39:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bc764328-264e-437d-838f-ebac54bf808b # CTA button url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5c9afca-2fc9-403b-90fb-e572fe452b5b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:39:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e0bbfb1d-1fee-4db7-a6b0-6cb937f67d00 # About section title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 802cbb10-4f35-4afc-9ffa-8b875da77b4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-12T08:39:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 22918af6-f86e-4ad2-a9d1-5328727f45e9 # About section text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7c70b16-9b4a-4317-baa9-211c1db348c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91ab2c90-f5ab-4ca8-b4c0-be72d73839a7
        userCondition: null
handle: homepage
hasTitleField: true
icon: null
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
