color: null
description: null
fieldLayouts:
  7e6713ea-fe06-4b72-a4ce-a4cbaa947262:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-14T11:09:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0fa056a-e069-4c6b-b3c7-28fc275eaf49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T11:11:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c854ee8e-d31d-41b5-a6b5-439ded6b83e4 # Section width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5088e6b1-b5e3-4c71-9009-238234156a5f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T11:11:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a2b84830-34a0-4780-bf03-08293ba5127c # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c6d24de-70cd-4991-873b-45c5f13b674d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T11:11:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f06dd89-2dcf-4ae6-9ea2-0ffecd508fa1 # Image height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b79507b-e06a-4cfe-87dc-ad78fae40b78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T11:11:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2510f397-c34c-4a8b-b10e-fb9b14599ee6 # Featured Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d57984f5-1015-464f-a6bf-626332c541cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T11:11:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e75f7d5c-c14a-4095-b070-a87cf4489180 # Hero title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1c147dd-93ed-47c0-aa14-91699eedde9d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T11:11:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8dff054f-3c9d-44a0-a554-925d24f53805 # Hero text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3edca0ff-dd71-4f35-a114-65317c5c613e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5902959f-9b63-4942-8332-8d982396295c
        userCondition: null
handle: indexPage
hasTitleField: true
icon: null
name: 'Index Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
