altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  19123efa-3a33-44e6-8b15-50012664df26:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-09T11:52:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 37111a7e-11bd-40c8-9deb-8000b575da9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3d61535-da6d-4133-a7f9-f086d6bda3d6
        userCondition: null
fs: local
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
