columnSuffix: null
handle: aboutSectionText
instructions: null
name: 'About section text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: b75c217c-fc11-41f6-b056-7f483eb2212f # Default
  createButtonLabel: null
  defaultTransform: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c5c244d6-e8ec-4134-8847-e59eb5136f70
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
