columnSuffix: null
handle: attribution
instructions: null
name: Attribution
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Who said this? (optional)'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
