columnSuffix: null
handle: caption
instructions: 'Optional visible caption below the image'
name: Caption
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: 200
  ckeConfig: null
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
