columnSuffix: null
handle: experienceType
instructions: 'How was this experience created?'
name: 'Experience Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Editorial Reportage'
        -
          - value
          - editorialReportage
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Community Story'
        -
          - value
          - communityStory
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
