columnSuffix: null
handle: shortQuote
instructions: null
name: 'Short Quote'
searchable: false
settings:
  byteLimit: null
  charLimit: 200
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'A key quote for teaser cards'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
