columnSuffix: null
handle: submitterEmail
instructions: null
name: 'Submitter Email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
