columnSuffix: null
handle: submitterLocation
instructions: null
name: 'Submitter Location'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: false
  initialRows: 4
  multiline: false
  placeholder: '"e.g., Giambellino, Milano"'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
