columnSuffix: null
handle: submitterStory
instructions: null
name: 'Submitter Story'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
