dateModified: 1766058706
email:
  fromEmail: me@nicovece.com
  fromName: Outring
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0a4e97ab-20db-490f-9aff-4ce8a944eca0: w1200 # w1200
    0e616ad3-9e17-4f84-8cf2-3f573b31208a: 'Submitter Email' # Submitter Email
    1f153368-e72f-4d41-9a33-2c0cc7769cfe: 'External Project URL' # External Project URL
    2c506b5d-c50c-4a0c-987d-ee5a0e597996: 'Pull Quote' # Pull Quote
    3a6099cc-52f1-4d82-a793-8fff632ccf70: 'Experience Types' # Experience Types
    03e18ea1-7651-41cd-9492-c899a3e46eca: 'Participation Phases' # Participation Phases
    3f06dd89-2dcf-4ae6-9ea2-0ffecd508fa1: 'Image height' # Image height
    5d1215b1-5277-45ff-add8-b9470c26338b: Text # Text
    5e85c8d8-050c-4f7b-83b5-8f5bb2c1609a: 'Alt Text' # Alt Text
    7c7a95e6-57d7-4355-9679-32d26c3c0a83: Role # Role
    7da6a3b4-58fb-435d-b0fe-cfd5a53a7fe2: Places # Places
    7eb89847-52c1-4cf3-8178-cddbc12e22bd: Attribution # Attribution
    7f1c25b6-7231-4cf2-96d8-b6c651140081: 'Site tagline' # Site tagline
    8b1eeb41-ed00-4e2d-ae3f-293ff76f96d6: Themes # Themes
    8b21baa7-1aaf-4641-a3f0-94997d5d755a: 'Participation Phases' # Participation Phases
    8dff054f-3c9d-44a0-a554-925d24f53805: 'Hero text' # Hero text
    8e125a51-39c8-4452-8313-84b56f8fd5fb: 'Rich Text' # Rich Text
    9b3aa930-2c46-4c7f-a9ce-3119712fb9a9: Stripped-down # Stripped-down
    9c8b9611-d687-4642-8647-d84d7a816609: 'Before Alt Text' # Before Alt Text
    22a9aad3-c553-4c77-b41c-bfb50d672c36: w400 # w400
    62bc0ef7-2ac1-4b54-b20d-b5029f396ce6: Outring # Outring
    65b3367e-a8c3-4edd-bbb0-102b193e2928: 'Themes Index' # Themes Index
    79dfdcd1-560d-402e-8eee-7c663bdbdb15: Experiences # Experiences
    096fcfd5-9243-4f20-a047-1925850af491: 'Places Index' # Places Index
    0178d46e-a81d-4be3-bab6-7481e2c62ee1: Experience # Experience
    0217ffe7-c5a5-465a-a8ea-fcc5e8839f81: 'Submitter Name' # Submitter Name
    598d0d21-8167-418b-b4c0-f5012fdd9a6b: Manifesto # Manifesto
    0905e205-4c22-4c63-88f1-fe6a62497607: City # City
    1418d0e3-127c-47e3-a914-2074712463c4: 'Before After' # Before After
    2289d566-365e-487f-9c76-a01fd1f73a07: 'Date of Experience' # Date of Experience
    2510f397-c34c-4a8b-b10e-fb9b14599ee6: 'Featured Image Caption' # Featured Image Caption
    2856f991-bc95-4a50-ae86-cdb6d7a75cce: 'Theme Color' # Theme Color
    9360bbed-4244-4034-a80e-cb0814742b75: 'Show in preview' # Show in preview
    22918af6-f86e-4ad2-a9d1-5328727f45e9: 'About section text' # About section text
    27000dd9-6752-4e6e-8c78-d46762a38049: 'Experience Type' # Experience Type
    46074d51-880d-400f-b390-512515e1246d: Homepage # Homepage
    99065c31-85bb-40f5-a596-9edb5964acd8: Homepage # Homepage
    632826db-933d-4fb9-a63e-c6173a02cf07: Place # Place
    695043cc-c5cc-41eb-af11-8a82b7e873a0: Photo # Photo
    811867f9-5d6c-43e8-a1ae-d294f0dbe229: Image # Image
    882949e2-a06f-4263-95b8-dd17ccde9d50: 'CTA button thext' # CTA button thext
    1190013e-63ae-4750-b14d-58b19474b584: 'Submitter Location' # Submitter Location
    22630847-d6e9-4cf9-a1c8-78d84d281486: 'Short Quote' # Short Quote
    a2b84830-34a0-4780-bf03-08293ba5127c: 'Featured Image' # Featured Image
    ace70b36-3361-492c-a3ff-086baadf1ca0: w2400 # w2400
    ad89808d-966d-4ce0-a7dc-5b390dfad2c8: w1600 # w1600
    af2a869f-7e80-45dc-a20f-c6dabafd3b85: 'Site info' # Site info
    af67dae9-339a-4f37-8d53-f8a337507e03: 'Index Page' # Index Page
    b0fe198f-199f-4d2e-ae35-2349dc2a9622: Description # Description
    b2d67bb8-0595-4356-a6ad-349dec9f11dd: Place # Place
    b75c217c-fc11-41f6-b056-7f483eb2212f: Default # Default
    bc764328-264e-437d-838f-ebac54bf808b: 'CTA button url' # CTA button url
    be1f3a1a-59dc-40d2-bf4c-640cd03d86a3: About # About
    c1a55f6f-a25c-4608-af2d-e290209cdad0: Manifesto # Manifesto
    c754eefd-99e6-4646-8399-3e26f08a4e9a: 'Image Block' # Image Block
    c854ee8e-d31d-41b5-a6b5-439ded6b83e4: 'Section width' # Section width
    cc978418-4e17-473f-a62f-71e2a6e8742d: 'Site display name' # Site display name
    cef5dec6-7bf0-46e1-afea-cdf7cefb9982: w800 # w800
    d2b7c10f-b013-4c41-a09d-60e005a5b8d1: Images # Images
    d3c2c606-4515-4be3-9780-cda4112337c0: Name # Name
    d4fc5d70-873a-4c16-9938-8dbc6f6e4b35: Outring # Outring
    d9517422-a093-4a22-a24a-5b8ebcd24c15: Person # Person
    da9f857b-c96d-4a51-bf9e-1145543329c6: 'People Involved' # People Involved
    dc3e09dc-ecd5-4bb4-867c-f1d24a4dcb40: Theme # Theme
    df5e3056-f611-4f43-9561-ba7ee0622c93: Quote # Quote
    e0bbfb1d-1fee-4db7-a6b0-6cb937f67d00: 'About section title' # About section title
    e8a7ebee-dfaa-4253-8107-0e1716a4b36e: 'After Image' # After Image
    e75f7d5c-c14a-4095-b070-a87cf4489180: 'Hero title' # Hero title
    eaf6a6e9-e328-4688-864e-9b23f3e55755: Caption # Caption
    ec82511a-62d1-43d6-9b3d-754139ae7565: Callout # Callout
    eee44d8f-a8f8-4c84-a202-5490cb708983: 'Voice Perspective' # Voice Perspective
    ef2e8135-8589-451c-853a-ae1b22c5547d: About # About
    f066fe0c-da43-4310-8dcc-e710b2f427a0: 'Submitter Story' # Submitter Story
    f08a310e-0e47-47a4-bb1c-51dc3436baba: 'After Alt Text' # After Alt Text
    f80a4df9-6931-4e2b-af3b-23d50be99dc6: 'Before Image' # Before Image
    f7523342-6e93-4849-89f8-1951759f8e05: Simple # Simple
    fe0b41ea-1d6b-4721-92d9-ad51f4ce6038: Body # Body
    fff6184b-15f7-4bc8-b79b-4555a163c116: Themes # Themes
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
    settings:
      enableCsrfProtection: '1'
      entryVariable: entry
      sections:
        __assoc__:
          -
            - 79dfdcd1-560d-402e-8eee-7c663bdbdb15 # Experiences
            -
              __assoc__:
                -
                  - sectionUid
                  - 79dfdcd1-560d-402e-8eee-7c663bdbdb15 # Experiences
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - ''
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 4076fbc9-0e83-4a87-b26c-2cf8cbc06ad5
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Outring
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
