fieldLayouts:
  756a4829-2eb4-44f3-8581-15f455662ead:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-13T18:05:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cc978418-4e17-473f-a62f-71e2a6e8742d # Site display name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5e26a38-170c-43bc-8382-e8ca97510b00
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-13T18:05:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f1c25b6-7231-4cf2-96d8-b6c651140081 # Site tagline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94c7cc53-b280-4a5e-990e-2d1495f12c2e
            userCondition: null
            warning: null
            width: 100
        name: 'Site info content'
        uid: 2a6198b1-640e-49ca-8ac6-91becd65ba3f
        userCondition: null
handle: siteInfo
name: 'Site info'
sortOrder: 1
