defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0178d46e-a81d-4be3-bab6-7481e2c62ee1 # Experience
handle: experiences
maxAuthors: 1
name: Experiences
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  62bc0ef7-2ac1-4b54-b20d-b5029f396ce6: # Outring
    enabledByDefault: true
    hasUrls: true
    template: experiences/_entry.twig
    uriFormat: 'experiences/{slug}'
type: channel
