defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 598d0d21-8167-418b-b4c0-f5012fdd9a6b # Manifesto
handle: manifesto
maxAuthors: 1
name: Manifesto
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  62bc0ef7-2ac1-4b54-b20d-b5029f396ce6: # Outring
    enabledByDefault: true
    hasUrls: true
    template: manifesto/_entry.twig
    uriFormat: manifesto
type: single
